# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c4561fa3761ba457c83fa7cf6aa64e5685fa99979c16601dd8b9f170ba1f0ebe7f63a09abfcea09f57c99b36871584193ad925e57a61fa203f11d531e4b8eca

test:
  secret_key_base: 4cf02ae836dd9291495b6e095c4153d2f6a72922c8138ae7af7af7ad7c868d32ef769d79c8412b10e1e3739339478fa6cafbf3e1ba667d78e6119e8f7f70895f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
